-- =========================================
-- Cleanup Script for Example Database Setup
-- =========================================

-- Use correct context
USE DATABASE EXAMPLE;
USE SCHEMA EXAMPLE;

-- Drop procedure first
DROP PROCEDURE IF EXISTS load_folder_data(STRING, STRING, STRING);
DROP PROCEDURE IF EXISTS load_dim_stores();
DROP PROCEDURE IF EXISTS load_dim_customers();
DROP PROCEDURE IF EXISTS load_dim_employees();
DROP PROCEDURE IF EXISTS load_dim_products();
DROP PROCEDURE IF EXISTS load_fact_transactions();

-- Drop tables
DROP TABLE IF EXISTS STORES;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS load_audit_log;
DROP TABLE IF EXISTS DIM_STORES;
DROP TABLE IF EXISTS DIM_CUSTOMERS;
DROP TABLE IF EXISTS DIM_EMPLOYEES;
DROP TABLE IF EXISTS DIM_PRODUCTS;
DROP TABLE IF EXISTS FACT_TRANSACTIONS;
DROP TABLE IF EXISTS DIM_TIME;

--Drop streams

DROP STREAM IF EXISTS STORES_STREAM;
DROP STREAM IF EXISTS CUSTOMERS_STREAM;
DROP STREAM IF EXISTS EMPLOYEES_STREAM;
DROP STREAM IF EXISTS PRODUCTS_STREAM;
DROP STREAM IF EXISTS TRANSACTIONS_STREAM;


--DROP VIEWS

DROP VIEW IF EXISTS DIM_DATE;

-- Drop file format
DROP FILE FORMAT IF EXISTS my_csv_format;

-- Drop stage
DROP STAGE IF EXISTS raw_files;

-- Drop schema
DROP SCHEMA IF EXISTS EXAMPLE;

-- Drop database
DROP DATABASE IF EXISTS EXAMPLE;