USE DATABASE EXAMPLE;
USE SCHEMA EXAMPLE;



CREATE OR REPLACE ROLE UK_ROLE;

GRANT ROLE UK_ROLE TO USER YOUR_USERNAME;


CREATE OR REPLACE ROW ACCESS POLICY country_rls
AS (country STRING)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'UK_ROLE'
            THEN country = 'UK'

        ELSE FALSE
    END;


ALTER TABLE customers
ADD ROW ACCESS POLICY country_rls
ON (COUNTRY);


USE ROLE UK_ROLE;

SELECT *
FROM customers;